version: "2.4"

networks:
  dev:
    driver: bridge

services:
  bw_bookstore:
    image: docker.io/library/bwbookstore
    container_name: bwbookstore-services
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=bwbookstore_db;Port=5432;Database=BWDbBookstore;Pooling=true;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - dev

  bwbookstore_db:
    image: postgres:latest
    container_name: bwbookstore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BWDbBookstore
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - bwbookstore_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  bwbookstore_data:
